import './glass.gif';
import './ceiling.jpg';
import './moon.gif';
import './podloga.jpg';
import './star.gif';
import './wall.jpg';
import './world.txt';

import './lessons/01.js';
import './lessons/02.js';
import './lessons/03.js';
import './lessons/04.js';
import './lessons/05.js';
import './lessons/06.js';
import './lessons/07.js';
import './lessons/08.js';
import './lessons/09.js';
import './lessons/10.js';
import './lessons/11.js';
